export const data = [
  {
    type_of: "article",
    id: 1748723,
    title: "Everything you need to know about GIT",
    description:
      "I'm sure you can imagine the importance of versioning code, so that we can revert changes and recover...",
    readable_publish_date: "Feb 5",
    slug: "everything-that-you-need-to-know-about-git-2440",
    path: "/reenatoteixeira/everything-that-you-need-to-know-about-git-2440",
    url: "https://dev.to/reenatoteixeira/everything-that-you-need-to-know-about-git-2440",
    comments_count: 19,
    public_reactions_count: 163,
    collection_id: null,
    published_timestamp: "2024-02-05T14:30:00Z",
    positive_reactions_count: 163,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fqu3vtabrpyb6q8kulm7p.png",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fqu3vtabrpyb6q8kulm7p.png",
    canonical_url:
      "https://dev.to/reenatoteixeira/everything-that-you-need-to-know-about-git-2440",
    created_at: "2024-02-01T16:34:35Z",
    edited_at: "2024-02-06T01:58:11Z",
    crossposted_at: null,
    published_at: "2024-02-05T14:30:00Z",
    last_comment_at: "2024-02-06T02:07:32Z",
    reading_time_minutes: 15,
    tag_list: ["beginners", "tutorial", "learning", "git"],
    tags: "beginners, tutorial, learning, git",
    user: {
      name: "Renato Teixeira",
      username: "reenatoteixeira",
      twitter_username: "reenato_q",
      github_username: "reenatoteixeira",
      user_id: 1257274,
      website_url: null,
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1257274%2Fd097d1d5-5d1c-4e9e-a6e7-e323ffe2a9e1.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1257274%2Fd097d1d5-5d1c-4e9e-a6e7-e323ffe2a9e1.png",
    },
  },
  {
    type_of: "article",
    id: 1752300,
    title: "Top 7 Featured DEV Posts of the Week",
    description:
      "A round up of the most-read and most-loved contributions from the community this past week",
    readable_publish_date: "Feb 5",
    slug: "top-7-featured-dev-posts-of-the-week-2j17",
    path: "/devteam/top-7-featured-dev-posts-of-the-week-2j17",
    url: "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-2j17",
    comments_count: 10,
    public_reactions_count: 19,
    collection_id: null,
    published_timestamp: "2024-02-05T18:55:08Z",
    positive_reactions_count: 19,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fizn8hfzc0bhki5h4cu15.jpg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fizn8hfzc0bhki5h4cu15.jpg",
    canonical_url:
      "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-2j17",
    created_at: "2024-02-05T15:32:13Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-05T18:55:08Z",
    last_comment_at: "2024-02-05T23:26:36Z",
    reading_time_minutes: 3,
    tag_list: ["top7"],
    tags: "top7",
    user: {
      name: "Erin A Olinick",
      username: "erinao",
      twitter_username: null,
      github_username: null,
      user_id: 1007771,
      website_url: null,
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1007771%2F7eec867a-5222-4c5f-8605-bf021dc997b8.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1007771%2F7eec867a-5222-4c5f-8605-bf021dc997b8.jpg",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
  },
  {
    type_of: "article",
    id: 1750103,
    title: "Music Monday — What are you listening to? (Homeland Edition II 🏠)",
    description:
      "cover image source: Giphy  That's right! We're bringing it back home again. The plan for this one is...",
    readable_publish_date: "Feb 5",
    slug: "music-monday-what-are-you-listening-to-homeland-edition-ii--3peb",
    path: "/devteam/music-monday-what-are-you-listening-to-homeland-edition-ii--3peb",
    url: "https://dev.to/devteam/music-monday-what-are-you-listening-to-homeland-edition-ii--3peb",
    comments_count: 13,
    public_reactions_count: 6,
    collection_id: 17887,
    published_timestamp: "2024-02-05T11:00:00Z",
    positive_reactions_count: 6,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fsli60166xnmmi3tzhh14.gif",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fsli60166xnmmi3tzhh14.gif",
    canonical_url:
      "https://dev.to/devteam/music-monday-what-are-you-listening-to-homeland-edition-ii--3peb",
    created_at: "2024-02-02T21:01:44Z",
    edited_at: "2024-02-02T21:46:30Z",
    crossposted_at: null,
    published_at: "2024-02-05T11:00:00Z",
    last_comment_at: "2024-02-05T19:38:30Z",
    reading_time_minutes: 2,
    tag_list: ["watercooler", "music", "discuss"],
    tags: "watercooler, music, discuss",
    user: {
      name: "Michael Tharrington",
      username: "michaeltharrington",
      twitter_username: "MichaelMadcat",
      github_username: "michael-tharrington",
      user_id: 38578,
      website_url: "https://dev.to/michaeltharrington",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F38578%2F05ce9c9d-43b7-4823-a423-f875a94edc27.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F38578%2F05ce9c9d-43b7-4823-a423-f875a94edc27.jpg",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
    flare_tag: {
      name: "watercooler",
      bg_color_hex: "#D0ECFF",
      text_color_hex: "#130074",
    },
  },
  {
    type_of: "article",
    id: 1752353,
    title: "Featured Mod of the Month: Fabrizio Bagalá",
    description:
      "In this series, we shine a spotlight 🔦 on the different DEV moderators — Trusted Members and Tag Mods...",
    readable_publish_date: "Feb 5",
    slug: "featured-mod-of-the-month-fabrizio-bagala-26ob",
    path: "/devteam/featured-mod-of-the-month-fabrizio-bagala-26ob",
    url: "https://dev.to/devteam/featured-mod-of-the-month-fabrizio-bagala-26ob",
    comments_count: 2,
    public_reactions_count: 16,
    collection_id: 22642,
    published_timestamp: "2024-02-05T19:53:45Z",
    positive_reactions_count: 16,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F3px7b5mvhppq2u3xabzr.jpeg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F3px7b5mvhppq2u3xabzr.jpeg",
    canonical_url:
      "https://dev.to/devteam/featured-mod-of-the-month-fabrizio-bagala-26ob",
    created_at: "2024-02-05T16:27:34Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-05T19:53:45Z",
    last_comment_at: "2024-02-05T23:46:05Z",
    reading_time_minutes: 6,
    tag_list: ["interview", "meta", "moderation", "community"],
    tags: "interview, meta, moderation, community",
    user: {
      name: "Michael Tharrington",
      username: "michaeltharrington",
      twitter_username: "MichaelMadcat",
      github_username: "michael-tharrington",
      user_id: 38578,
      website_url: "https://dev.to/michaeltharrington",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F38578%2F05ce9c9d-43b7-4823-a423-f875a94edc27.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F38578%2F05ce9c9d-43b7-4823-a423-f875a94edc27.jpg",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
  },
  {
    type_of: "article",
    id: 1748895,
    title: "Introducing Our New Writing Streak Badges! ✏️👌",
    description:
      "Today we are very happy to present you all with our first badge update of the new year! You may have...",
    readable_publish_date: "Feb 5",
    slug: "introducing-our-new-writing-streak-badges-2jh9",
    path: "/devteam/introducing-our-new-writing-streak-badges-2jh9",
    url: "https://dev.to/devteam/introducing-our-new-writing-streak-badges-2jh9",
    comments_count: 8,
    public_reactions_count: 28,
    collection_id: 24286,
    published_timestamp: "2024-02-05T16:36:00Z",
    positive_reactions_count: 28,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fr1mzd5qthxcnlpmrhlqw.jpg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fr1mzd5qthxcnlpmrhlqw.jpg",
    canonical_url:
      "https://dev.to/devteam/introducing-our-new-writing-streak-badges-2jh9",
    created_at: "2024-02-01T19:28:11Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-05T16:36:00Z",
    last_comment_at: "2024-02-06T02:01:08Z",
    reading_time_minutes: 1,
    tag_list: ["meta", "design", "badges"],
    tags: "meta, design, badges",
    user: {
      name: "dev.to staff",
      username: "thepracticaldev",
      twitter_username: "ThePracticalDev",
      github_username: null,
      user_id: 3,
      website_url: "https://dev.to",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
  },
  {
    type_of: "article",
    id: 1752446,
    title: "DevRel Discussion",
    description:
      "Happy Monday to those who celebrate! 😂   This week's DevRel Discussion is a fun one:  What is...",
    readable_publish_date: "Feb 5",
    slug: "devrel-discussion-11kl",
    path: "/lizzzzz/devrel-discussion-11kl",
    url: "https://dev.to/lizzzzz/devrel-discussion-11kl",
    comments_count: 7,
    public_reactions_count: 3,
    collection_id: null,
    published_timestamp: "2024-02-05T18:27:01Z",
    positive_reactions_count: 3,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F7x8hjhzd69pqo3pbraex.png",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F7x8hjhzd69pqo3pbraex.png",
    canonical_url: "https://dev.to/lizzzzz/devrel-discussion-11kl",
    created_at: "2024-02-05T18:27:02Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-05T18:27:01Z",
    last_comment_at: "2024-02-05T21:57:37Z",
    reading_time_minutes: 1,
    tag_list: ["discuss", "devrel", "music"],
    tags: "discuss, devrel, music",
    user: {
      name: "Liz Acosta",
      username: "lizzzzz",
      twitter_username: null,
      github_username: "liz-acosta",
      user_id: 520299,
      website_url: "https://liz-acosta.com/",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F520299%2F38de40f4-43b2-4a0d-a7cc-2fa6494ac4b3.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F520299%2F38de40f4-43b2-4a0d-a7cc-2fa6494ac4b3.png",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 1752253,
    title: "Six months with GitHub Copilot",
    description:
      "I’ve been coding with GitHub Copilot over the past six months, and I’ve steadily seen it improve my...",
    readable_publish_date: "Feb 5",
    slug: "six-months-with-github-copilot-286e",
    path: "/richarddli/six-months-with-github-copilot-286e",
    url: "https://dev.to/richarddli/six-months-with-github-copilot-286e",
    comments_count: 2,
    public_reactions_count: 7,
    collection_id: null,
    published_timestamp: "2024-02-05T14:34:33Z",
    positive_reactions_count: 7,
    cover_image: null,
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F0ml83qy6xkv5dinjvipq.png",
    canonical_url: "https://www.thelis.org/blog/github-copilot",
    created_at: "2024-02-05T14:28:16Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-05T14:34:33Z",
    last_comment_at: "2024-02-05T22:56:37Z",
    reading_time_minutes: 5,
    tag_list: ["githubcopilot", "programming", "python", "machinelearning"],
    tags: "githubcopilot, programming, python, machinelearning",
    user: {
      name: "Richard Li",
      username: "richarddli",
      twitter_username: null,
      github_username: "richarddli",
      user_id: 31455,
      website_url: "https://www.amorphousdata.com",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F31455%2F37e66a45-999e-4c18-a09f-941c482a828f.jpeg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F31455%2F37e66a45-999e-4c18-a09f-941c482a828f.jpeg",
    },
  },
  {
    type_of: "article",
    id: 1747428,
    title: "How Do You Shift the Focus from Individual to Collective Success?",
    description:
      "How does your team shift focus from individual achievements to collective results? Share examples of...",
    readable_publish_date: "Feb 5",
    slug: "how-do-you-shift-the-focus-from-individual-to-collective-success-433l",
    path: "/devteam/how-do-you-shift-the-focus-from-individual-to-collective-success-433l",
    url: "https://dev.to/devteam/how-do-you-shift-the-focus-from-individual-to-collective-success-433l",
    comments_count: 1,
    public_reactions_count: 1,
    collection_id: null,
    published_timestamp: "2024-02-05T00:00:00Z",
    positive_reactions_count: 1,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ft56k5s0uyiyk7kbc94z0.png",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ft56k5s0uyiyk7kbc94z0.png",
    canonical_url:
      "https://dev.to/devteam/how-do-you-shift-the-focus-from-individual-to-collective-success-433l",
    created_at: "2024-01-31T17:15:30Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-05T00:00:00Z",
    last_comment_at: "2024-02-05T07:03:37Z",
    reading_time_minutes: 1,
    tag_list: ["discuss"],
    tags: "discuss",
    user: {
      name: "dev.to staff",
      username: "thepracticaldev",
      twitter_username: "ThePracticalDev",
      github_username: null,
      user_id: 3,
      website_url: "https://dev.to",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 1751976,
    title:
      'How the "The Three Little Pigs" Story Helped Me Become A Better Frontend Developer',
    description:
      "Once upon a time, there was an old mother pig who had three little pigs 🐷.  Since she didn't have...",
    readable_publish_date: "Feb 5",
    slug: "how-the-the-three-little-pigs-story-helped-me-become-a-senior-frontend-developer-2ikh",
    path: "/_ndeyefatoudiop/how-the-the-three-little-pigs-story-helped-me-become-a-senior-frontend-developer-2ikh",
    url: "https://dev.to/_ndeyefatoudiop/how-the-the-three-little-pigs-story-helped-me-become-a-senior-frontend-developer-2ikh",
    comments_count: 0,
    public_reactions_count: 1,
    collection_id: null,
    published_timestamp: "2024-02-05T12:35:24Z",
    positive_reactions_count: 1,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fk27rczt5m5ptw5ouk4hy.jpg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fk27rczt5m5ptw5ouk4hy.jpg",
    canonical_url:
      "https://dev.to/_ndeyefatoudiop/how-the-the-three-little-pigs-story-helped-me-become-a-senior-frontend-developer-2ikh",
    created_at: "2024-02-05T09:21:38Z",
    edited_at: "2024-02-05T14:21:16Z",
    crossposted_at: null,
    published_at: "2024-02-05T12:35:24Z",
    last_comment_at: "2024-02-05T12:35:24Z",
    reading_time_minutes: 2,
    tag_list: ["webdev", "beginners", "javascript", "frontend"],
    tags: "webdev, beginners, javascript, frontend",
    user: {
      name: "Ndeye Fatou Diop",
      username: "_ndeyefatoudiop",
      twitter_username: "joyancefa",
      github_username: "nfdiop",
      user_id: 440984,
      website_url: "https://ndeyefatoudiop.substack.com/",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F440984%2Fe06f206e-d5aa-428b-9034-e1f607c5a943.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F440984%2Fe06f206e-d5aa-428b-9034-e1f607c5a943.jpg",
    },
  },
  {
    type_of: "article",
    id: 1717649,
    title: "Caption This! 🤔💭",
    description:
      "Think you've got what it takes to whip up the cleverest caption for this image? Give it a...",
    readable_publish_date: "Feb 5",
    slug: "caption-this-2n8e",
    path: "/devteam/caption-this-2n8e",
    url: "https://dev.to/devteam/caption-this-2n8e",
    comments_count: 9,
    public_reactions_count: 6,
    collection_id: null,
    published_timestamp: "2024-02-05T00:00:00Z",
    positive_reactions_count: 6,
    cover_image: null,
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fibwx82wh0ivuvvcbjsrm.png",
    canonical_url: "https://dev.to/devteam/caption-this-2n8e",
    created_at: "2024-01-05T00:53:52Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-05T00:00:00Z",
    last_comment_at: "2024-02-05T14:51:59Z",
    reading_time_minutes: 1,
    tag_list: ["watercooler"],
    tags: "watercooler",
    user: {
      name: "dev.to staff",
      username: "thepracticaldev",
      twitter_username: "ThePracticalDev",
      github_username: null,
      user_id: 3,
      website_url: "https://dev.to",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
    flare_tag: {
      name: "watercooler",
      bg_color_hex: "#D0ECFF",
      text_color_hex: "#130074",
    },
  },
  {
    type_of: "article",
    id: 1747477,
    title: "Meet 'Awesome Topics'",
    description:
      "Meet 'Awesome Topics,' a new GitHub repository in the 'Awesome' movement. Unlike traditional...",
    readable_publish_date: "Jan 31",
    slug: "meet-awesome-topics-mkk",
    path: "/mahmoudz/meet-awesome-topics-mkk",
    url: "https://dev.to/mahmoudz/meet-awesome-topics-mkk",
    comments_count: 0,
    public_reactions_count: 1,
    collection_id: null,
    published_timestamp: "2024-01-31T17:25:08Z",
    positive_reactions_count: 1,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fjvre81r4p6opblhvhqk7.png",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fjvre81r4p6opblhvhqk7.png",
    canonical_url: "https://dev.to/mahmoudz/meet-awesome-topics-mkk",
    created_at: "2024-01-31T17:25:08Z",
    edited_at: "2024-01-31T17:26:31Z",
    crossposted_at: null,
    published_at: "2024-01-31T17:25:08Z",
    last_comment_at: "2024-01-31T17:25:08Z",
    reading_time_minutes: 1,
    tag_list: ["awesome", "learning", "softwareengineering"],
    tags: "awesome, learning, softwareengineering",
    user: {
      name: "Mahmoud Zalt",
      username: "mahmoudz",
      twitter_username: "Mahmoud_Zalt",
      github_username: "Mahmoudz",
      user_id: 195751,
      website_url: "http://zalt.me",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F195751%2F3ebdc2c1-7958-4c66-8ade-80a27739c15c.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F195751%2F3ebdc2c1-7958-4c66-8ade-80a27739c15c.png",
    },
  },
  {
    type_of: "article",
    id: 1747502,
    title: "#DEVResolutions2024: Wrapping Up a Month of Wins 🏆",
    description:
      "As we bid adieu to January, a heartfelt thank you resonates through the DEV Community! 🙌 Your...",
    readable_publish_date: "Feb 1",
    slug: "devresolutions2024-wrapping-up-a-month-of-wins-350d",
    path: "/devteam/devresolutions2024-wrapping-up-a-month-of-wins-350d",
    url: "https://dev.to/devteam/devresolutions2024-wrapping-up-a-month-of-wins-350d",
    comments_count: 2,
    public_reactions_count: 11,
    collection_id: null,
    published_timestamp: "2024-02-01T15:36:05Z",
    positive_reactions_count: 11,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F5w19upp1u6zr0d6m6g0d.jpg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F5w19upp1u6zr0d6m6g0d.jpg",
    canonical_url:
      "https://dev.to/devteam/devresolutions2024-wrapping-up-a-month-of-wins-350d",
    created_at: "2024-01-31T18:13:43Z",
    edited_at: "2024-02-01T15:36:42Z",
    crossposted_at: null,
    published_at: "2024-02-01T15:36:05Z",
    last_comment_at: "2024-02-02T17:29:00Z",
    reading_time_minutes: 2,
    tag_list: ["devresolutions2024"],
    tags: "devresolutions2024",
    user: {
      name: "dev.to staff",
      username: "thepracticaldev",
      twitter_username: "ThePracticalDev",
      github_username: null,
      user_id: 3,
      website_url: "https://dev.to",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
  },
  {
    type_of: "article",
    id: 1728586,
    title: "What was your win this week?",
    description:
      "Hey my peeps! 👋  Hope everybody is doing well this Friday! 🥳  Looking back on this past week, what...",
    readable_publish_date: "Feb 2",
    slug: "what-was-your-win-this-week-cga",
    path: "/devteam/what-was-your-win-this-week-cga",
    url: "https://dev.to/devteam/what-was-your-win-this-week-cga",
    comments_count: 52,
    public_reactions_count: 24,
    collection_id: null,
    published_timestamp: "2024-02-02T11:00:00Z",
    positive_reactions_count: 24,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F4a9p16hwa372gwfnn235.jpg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F4a9p16hwa372gwfnn235.jpg",
    canonical_url: "https://dev.to/devteam/what-was-your-win-this-week-cga",
    created_at: "2024-01-15T22:07:24Z",
    edited_at: "2024-01-17T17:35:14Z",
    crossposted_at: null,
    published_at: "2024-02-02T11:00:00Z",
    last_comment_at: "2024-02-06T01:24:56Z",
    reading_time_minutes: 1,
    tag_list: ["discuss", "weeklyretro"],
    tags: "discuss, weeklyretro",
    user: {
      name: "Michael Tharrington",
      username: "michaeltharrington",
      twitter_username: "MichaelMadcat",
      github_username: "michael-tharrington",
      user_id: 38578,
      website_url: "https://dev.to/michaeltharrington",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F38578%2F05ce9c9d-43b7-4823-a423-f875a94edc27.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F38578%2F05ce9c9d-43b7-4823-a423-f875a94edc27.jpg",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 1744036,
    title:
      "What project new features or changes are you most excited about recently?",
    description:
      "What project updates have you been really excited about lately?  Is there something you’ve been...",
    readable_publish_date: "Jan 28",
    slug: "what-project-new-features-or-changes-are-you-most-excited-about-recently-3042",
    path: "/bekahhw/what-project-new-features-or-changes-are-you-most-excited-about-recently-3042",
    url: "https://dev.to/bekahhw/what-project-new-features-or-changes-are-you-most-excited-about-recently-3042",
    comments_count: 1,
    public_reactions_count: 3,
    collection_id: null,
    published_timestamp: "2024-01-28T21:56:18Z",
    positive_reactions_count: 3,
    cover_image: null,
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fx1y93dk427120wny2yar.png",
    canonical_url:
      "https://dev.to/bekahhw/what-project-new-features-or-changes-are-you-most-excited-about-recently-3042",
    created_at: "2024-01-28T21:56:18Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-01-28T21:56:18Z",
    last_comment_at: "2024-01-29T16:31:55Z",
    reading_time_minutes: 1,
    tag_list: ["discuss"],
    tags: "discuss",
    user: {
      name: "BekahHW",
      username: "bekahhw",
      twitter_username: "BekahHW",
      github_username: "BekahHW",
      user_id: 345658,
      website_url: "https://bekahhw.com/",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F345658%2Fa72b6b8b-b954-47fb-8919-ab380905f26b.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F345658%2Fa72b6b8b-b954-47fb-8919-ab380905f26b.jpg",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 1751276,
    title: "Any advice for someone who wants to start learning React.js?",
    description: "A post by Jr",
    readable_publish_date: "Feb 4",
    slug: "any-advice-for-someone-who-wants-to-start-learning-reactjs-1omd",
    path: "/jr01/any-advice-for-someone-who-wants-to-start-learning-reactjs-1omd",
    url: "https://dev.to/jr01/any-advice-for-someone-who-wants-to-start-learning-reactjs-1omd",
    comments_count: 21,
    public_reactions_count: 9,
    collection_id: null,
    published_timestamp: "2024-02-04T12:51:58Z",
    positive_reactions_count: 9,
    cover_image: null,
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fijd4jf14l6j0hrbl7fyh.png",
    canonical_url:
      "https://dev.to/jr01/any-advice-for-someone-who-wants-to-start-learning-reactjs-1omd",
    created_at: "2024-02-04T12:51:58Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-04T12:51:58Z",
    last_comment_at: "2024-02-06T01:43:08Z",
    reading_time_minutes: 0,
    tag_list: ["react", "beginners", "javascript", "programming"],
    tags: "react, beginners, javascript, programming",
    user: {
      name: "Jr",
      username: "jr01",
      twitter_username: null,
      github_username: null,
      user_id: 1272476,
      website_url: null,
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1272476%2F072fddd5-3918-485c-8ca7-a31290272496.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1272476%2F072fddd5-3918-485c-8ca7-a31290272496.jpg",
    },
  },
  {
    type_of: "article",
    id: 1752359,
    title: "Meme Monday",
    description:
      "Meme Monday!  Today's cover image comes from last week's thread.  DEV is an inclusive space! Humor in...",
    readable_publish_date: "Feb 5",
    slug: "meme-monday-27n8",
    path: "/ben/meme-monday-27n8",
    url: "https://dev.to/ben/meme-monday-27n8",
    comments_count: 35,
    public_reactions_count: 21,
    collection_id: null,
    published_timestamp: "2024-02-05T16:35:32Z",
    positive_reactions_count: 21,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fim17d7s35edaiugffau4.png",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fim17d7s35edaiugffau4.png",
    canonical_url: "https://dev.to/ben/meme-monday-27n8",
    created_at: "2024-02-05T16:35:33Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-05T16:35:32Z",
    last_comment_at: "2024-02-06T01:58:16Z",
    reading_time_minutes: 1,
    tag_list: ["discuss", "watercooler", "jokes"],
    tags: "discuss, watercooler, jokes",
    user: {
      name: "Ben Halpern",
      username: "ben",
      twitter_username: "bendhalpern",
      github_username: "benhalpern",
      user_id: 1,
      website_url: "http://benhalpern.com",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 1750968,
    title: "What is The Best Way to Learn a Coding Language?",
    description:
      "There is many ways you can learn to code. You can learn to code from a book, from an online code...",
    readable_publish_date: "Feb 4",
    slug: "what-is-the-best-way-to-learn-a-coding-language-50dc",
    path: "/anitaolsen/what-is-the-best-way-to-learn-a-coding-language-50dc",
    url: "https://dev.to/anitaolsen/what-is-the-best-way-to-learn-a-coding-language-50dc",
    comments_count: 3,
    public_reactions_count: 4,
    collection_id: null,
    published_timestamp: "2024-02-04T14:43:55Z",
    positive_reactions_count: 4,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fkxoi6yjnpf26mrvcn3f1.png",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fkxoi6yjnpf26mrvcn3f1.png",
    canonical_url:
      "https://dev.to/anitaolsen/what-is-the-best-way-to-learn-a-coding-language-50dc",
    created_at: "2024-02-04T01:19:16Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-04T14:43:55Z",
    last_comment_at: "2024-02-05T21:38:26Z",
    reading_time_minutes: 1,
    tag_list: ["discuss", "coding"],
    tags: "discuss, coding",
    user: {
      name: "Anita Olsen",
      username: "anitaolsen",
      twitter_username: null,
      github_username: null,
      user_id: 1195604,
      website_url: "https://www.olsenanita.com/",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1195604%2Fbe44eb20-9829-4104-b87a-4ba4d5549ed7.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1195604%2Fbe44eb20-9829-4104-b87a-4ba4d5549ed7.jpg",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 1751310,
    title:
      "Simplifying Data Analysis With AI and DevTools - for the non-Python developer!",
    description:
      "As an app developer you've probably generated (or accessed) a lot of data, and wished you had expertise to analyze and visualize the results. But you're not a Python developer! How can you get productive quickly? In this @PyDataNYC 2023 talk, I show you 4 tools and a process to jumpstart your data science journey.",
    readable_publish_date: "Feb 4",
    slug: "simplifying-data-analysis-with-ai-and-devtools-for-the-non-python-developer-g94",
    path: "/azure/simplifying-data-analysis-with-ai-and-devtools-for-the-non-python-developer-g94",
    url: "https://dev.to/azure/simplifying-data-analysis-with-ai-and-devtools-for-the-non-python-developer-g94",
    comments_count: 0,
    public_reactions_count: 4,
    collection_id: 25819,
    published_timestamp: "2024-02-04T17:17:12Z",
    positive_reactions_count: 4,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F4and0vjp8li5c3in78bt.png",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F4and0vjp8li5c3in78bt.png",
    canonical_url:
      "https://dev.to/azure/simplifying-data-analysis-with-ai-and-devtools-for-the-non-python-developer-g94",
    created_at: "2024-02-04T13:40:37Z",
    edited_at: "2024-02-04T17:17:20Z",
    crossposted_at: null,
    published_at: "2024-02-04T17:17:12Z",
    last_comment_at: "2024-02-04T17:17:12Z",
    reading_time_minutes: 6,
    tag_list: ["python", "datascience", "beginners", "ai"],
    tags: "python, datascience, beginners, ai",
    user: {
      name: "Nitya Narasimhan, Ph.D",
      username: "nitya",
      twitter_username: "nitya",
      github_username: "nitya",
      user_id: 8619,
      website_url: "https://nitya.dev",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F8619%2F6cdad4c9-6dc7-4b27-85bd-7b58fdb527da.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F8619%2F6cdad4c9-6dc7-4b27-85bd-7b58fdb527da.png",
    },
    organization: {
      name: "Microsoft Azure",
      username: "azure",
      slug: "azure",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F512%2F64ce0b82-730d-4ca0-8359-2c21513a0063.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F512%2F64ce0b82-730d-4ca0-8359-2c21513a0063.jpg",
    },
  },
  {
    type_of: "article",
    id: 1749310,
    title:
      '"🌟 Friday Fun with Dev Community: Celebrating Coding Adventures! 🎉"',
    description:
      "👋 Hey dev community! It's Friday, which means it's time for some tech talk and celebration! 🎉 Here's...",
    readable_publish_date: "Feb 2",
    slug: "-friday-fun-with-dev-community-celebrating-coding-adventures--g7h",
    path: "/madzimai/-friday-fun-with-dev-community-celebrating-coding-adventures--g7h",
    url: "https://dev.to/madzimai/-friday-fun-with-dev-community-celebrating-coding-adventures--g7h",
    comments_count: 0,
    public_reactions_count: 5,
    collection_id: null,
    published_timestamp: "2024-02-02T08:08:31Z",
    positive_reactions_count: 5,
    cover_image: null,
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fmbe6eg5bsfr4rrcsb95h.png",
    canonical_url:
      "https://dev.to/madzimai/-friday-fun-with-dev-community-celebrating-coding-adventures--g7h",
    created_at: "2024-02-02T08:08:31Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-02T08:08:31Z",
    last_comment_at: "2024-02-02T08:08:31Z",
    reading_time_minutes: 2,
    tag_list: ["discuss", "beginners", "developers"],
    tags: "discuss, beginners, developers",
    user: {
      name: "Netsai",
      username: "madzimai",
      twitter_username: null,
      github_username: "madzimai",
      user_id: 410449,
      website_url: null,
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F410449%2F817fbefd-1d54-41fd-82df-93859db3da16.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F410449%2F817fbefd-1d54-41fd-82df-93859db3da16.png",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 1745732,
    title: "Enabling children in disastrous regions through technology",
    description:
      "I was born in a culture that promotes humble behavior and values selflessness and altruism in human...",
    readable_publish_date: "Jan 30",
    slug: "enabling-children-in-disastrous-regions-through-technology-3209",
    path: "/a0m0rajab/enabling-children-in-disastrous-regions-through-technology-3209",
    url: "https://dev.to/a0m0rajab/enabling-children-in-disastrous-regions-through-technology-3209",
    comments_count: 0,
    public_reactions_count: 12,
    collection_id: null,
    published_timestamp: "2024-01-30T18:20:09Z",
    positive_reactions_count: 12,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ff2u71inehex7ckgtqa38.jpeg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ff2u71inehex7ckgtqa38.jpeg",
    canonical_url:
      "https://dev.to/a0m0rajab/enabling-children-in-disastrous-regions-through-technology-3209",
    created_at: "2024-01-30T09:38:28Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-01-30T18:20:09Z",
    last_comment_at: "2024-01-30T18:20:09Z",
    reading_time_minutes: 7,
    tag_list: ["learning", "coding", "community", "career"],
    tags: "learning, coding, community, career",
    user: {
      name: "Abdurrahman Rajab",
      username: "a0m0rajab",
      twitter_username: null,
      github_username: "a0m0rajab",
      user_id: 500476,
      website_url: "https://www.abdurrahmanrajab.com/",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F500476%2F5c7417cb-b8fd-4388-9f59-faed77cb21ce.jpeg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F500476%2F5c7417cb-b8fd-4388-9f59-faed77cb21ce.jpeg",
    },
  },
  {
    type_of: "article",
    id: 1746551,
    title: "DevRel Discussions",
    description:
      "A theme I've noticed in DevRel is the discussion about what kind of role AI will play in the practice...",
    readable_publish_date: "Jan 31",
    slug: "devrel-discussions-aef",
    path: "/lizzzzz/devrel-discussions-aef",
    url: "https://dev.to/lizzzzz/devrel-discussions-aef",
    comments_count: 1,
    public_reactions_count: 2,
    collection_id: null,
    published_timestamp: "2024-01-31T00:41:05Z",
    positive_reactions_count: 2,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Foas6h7nkhv6obsiidio5.png",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Foas6h7nkhv6obsiidio5.png",
    canonical_url: "https://dev.to/lizzzzz/devrel-discussions-aef",
    created_at: "2024-01-31T00:36:36Z",
    edited_at: "2024-01-31T16:06:47Z",
    crossposted_at: null,
    published_at: "2024-01-31T00:41:05Z",
    last_comment_at: "2024-01-31T16:10:33Z",
    reading_time_minutes: 1,
    tag_list: ["devrel", "ai", "discuss"],
    tags: "devrel, ai, discuss",
    user: {
      name: "Liz Acosta",
      username: "lizzzzz",
      twitter_username: null,
      github_username: "liz-acosta",
      user_id: 520299,
      website_url: "https://liz-acosta.com/",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F520299%2F38de40f4-43b2-4a0d-a7cc-2fa6494ac4b3.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F520299%2F38de40f4-43b2-4a0d-a7cc-2fa6494ac4b3.png",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 1717647,
    title: "Caption This! 🤔💭",
    description:
      "Ready to unleash your inner wordsmith? We need your wit to crack the code behind this picture-perfect...",
    readable_publish_date: "Jan 29",
    slug: "caption-this-ol6",
    path: "/devteam/caption-this-ol6",
    url: "https://dev.to/devteam/caption-this-ol6",
    comments_count: 14,
    public_reactions_count: 5,
    collection_id: null,
    published_timestamp: "2024-01-29T00:00:00Z",
    positive_reactions_count: 5,
    cover_image: null,
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fc6u82e3ctsuhd7m1t1a6.png",
    canonical_url: "https://dev.to/devteam/caption-this-ol6",
    created_at: "2024-01-05T00:49:37Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-01-29T00:00:00Z",
    last_comment_at: "2024-01-30T14:20:51Z",
    reading_time_minutes: 1,
    tag_list: ["watercooler"],
    tags: "watercooler",
    user: {
      name: "dev.to staff",
      username: "thepracticaldev",
      twitter_username: "ThePracticalDev",
      github_username: null,
      user_id: 3,
      website_url: "https://dev.to",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
    flare_tag: {
      name: "watercooler",
      bg_color_hex: "#D0ECFF",
      text_color_hex: "#130074",
    },
  },
  {
    type_of: "article",
    id: 1742510,
    title: "Solving the CIA Kryptos Code (Part 1)",
    description:
      "You can find all the code for this series on GitHub.  On the campus of CIA headquarters in Virginia,...",
    readable_publish_date: "Jan 26",
    slug: "solving-the-cia-kryptos-code-part-1-131e",
    path: "/isaacdlyman/solving-the-cia-kryptos-code-part-1-131e",
    url: "https://dev.to/isaacdlyman/solving-the-cia-kryptos-code-part-1-131e",
    comments_count: 0,
    public_reactions_count: 7,
    collection_id: 26199,
    published_timestamp: "2024-01-26T22:52:00Z",
    positive_reactions_count: 7,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F8uqzn666fv3ue94f2kie.jpg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F8uqzn666fv3ue94f2kie.jpg",
    canonical_url: "https://isaaclyman.com/blog/posts/kryptos-1/",
    created_at: "2024-01-26T22:57:06Z",
    edited_at: "2024-01-28T20:44:56Z",
    crossposted_at: null,
    published_at: "2024-01-26T22:52:00Z",
    last_comment_at: "2024-01-26T22:52:00Z",
    reading_time_minutes: 7,
    tag_list: ["cryptography", "cryptanalysis", "typescript"],
    tags: "cryptography, cryptanalysis, typescript",
    user: {
      name: "Isaac Lyman",
      username: "isaacdlyman",
      twitter_username: null,
      github_username: "isaaclyman",
      user_id: 572,
      website_url: "http://isaaclyman.com",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F572%2Fdb44b500-c4c1-4300-b0bd-f9fdc0f0d977.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F572%2Fdb44b500-c4c1-4300-b0bd-f9fdc0f0d977.jpg",
    },
  },
  {
    type_of: "article",
    id: 1728581,
    title: "What are you learning about this weekend? 🧠",
    description:
      "Hey y'all! 👋  Hope you're all enjoying your weekends. 🙌  Whether you're sharpening your JS skills,...",
    readable_publish_date: "Feb 3",
    slug: "what-are-you-learning-about-this-weekend-3b6",
    path: "/devteam/what-are-you-learning-about-this-weekend-3b6",
    url: "https://dev.to/devteam/what-are-you-learning-about-this-weekend-3b6",
    comments_count: 18,
    public_reactions_count: 7,
    collection_id: null,
    published_timestamp: "2024-02-03T14:00:00Z",
    positive_reactions_count: 7,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fthxk1wz0pnted6ij469g.jpg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fthxk1wz0pnted6ij469g.jpg",
    canonical_url:
      "https://dev.to/devteam/what-are-you-learning-about-this-weekend-3b6",
    created_at: "2024-01-15T21:56:01Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-03T14:00:00Z",
    last_comment_at: "2024-02-05T15:46:20Z",
    reading_time_minutes: 1,
    tag_list: ["codenewbie", "learning", "beginners", "discuss"],
    tags: "codenewbie, learning, beginners, discuss",
    user: {
      name: "Michael Tharrington",
      username: "michaeltharrington",
      twitter_username: "MichaelMadcat",
      github_username: "michael-tharrington",
      user_id: 38578,
      website_url: "https://dev.to/michaeltharrington",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F38578%2F05ce9c9d-43b7-4823-a423-f875a94edc27.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F38578%2F05ce9c9d-43b7-4823-a423-f875a94edc27.jpg",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 1745114,
    title: "Top 7 Featured DEV Posts of the Week",
    description:
      "A round up of the most-read and most-loved contributions from the community this past week",
    readable_publish_date: "Jan 29",
    slug: "top-7-featured-dev-posts-of-the-week-3jad",
    path: "/devteam/top-7-featured-dev-posts-of-the-week-3jad",
    url: "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-3jad",
    comments_count: 9,
    public_reactions_count: 44,
    collection_id: null,
    published_timestamp: "2024-01-29T19:01:13Z",
    positive_reactions_count: 44,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fizn8hfzc0bhki5h4cu15.jpg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fizn8hfzc0bhki5h4cu15.jpg",
    canonical_url:
      "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-3jad",
    created_at: "2024-01-29T18:56:51Z",
    edited_at: "2024-01-30T14:59:43Z",
    crossposted_at: null,
    published_at: "2024-01-29T19:01:13Z",
    last_comment_at: "2024-02-02T04:22:58Z",
    reading_time_minutes: 3,
    tag_list: ["top7"],
    tags: "top7",
    user: {
      name: "Erin A Olinick",
      username: "erinao",
      twitter_username: null,
      github_username: null,
      user_id: 1007771,
      website_url: null,
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1007771%2F7eec867a-5222-4c5f-8605-bf021dc997b8.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1007771%2F7eec867a-5222-4c5f-8605-bf021dc997b8.jpg",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
  },
  {
    type_of: "article",
    id: 1747992,
    title: "Font Size Considerations for Accessibility",
    description:
      "Discussions about accessibility, especially in software development, often center around screen...",
    readable_publish_date: "Feb 2",
    slug: "font-size-considerations-for-accessibility-p5a",
    path: "/eevajonnapanula/font-size-considerations-for-accessibility-p5a",
    url: "https://dev.to/eevajonnapanula/font-size-considerations-for-accessibility-p5a",
    comments_count: 3,
    public_reactions_count: 27,
    collection_id: null,
    published_timestamp: "2024-02-02T09:53:00Z",
    positive_reactions_count: 27,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fglctjdhc34033pau50f6.png",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fglctjdhc34033pau50f6.png",
    canonical_url:
      "https://eevis.codes/blog/2024-02-02/font-size-considerations-for-accessibility/",
    created_at: "2024-02-01T05:16:50Z",
    edited_at: "2024-02-02T03:49:37Z",
    crossposted_at: null,
    published_at: "2024-02-02T09:53:00Z",
    last_comment_at: "2024-02-03T15:08:09Z",
    reading_time_minutes: 6,
    tag_list: ["a11y", "android", "mobile", "programming"],
    tags: "a11y, android, mobile, programming",
    user: {
      name: "Eevis",
      username: "eevajonnapanula",
      twitter_username: null,
      github_username: "eevajonnapanula",
      user_id: 201004,
      website_url: "https://eevis.codes",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F201004%2Ff567403b-648c-4922-996e-a95132d48cbe.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F201004%2Ff567403b-648c-4922-996e-a95132d48cbe.jpg",
    },
  },
  {
    type_of: "article",
    id: 1749842,
    title: "Make Invalid States Unrepresentable",
    description:
      "Suppose you have a Person class in your program, and that a Person has an age. What type should the...",
    readable_publish_date: "Feb 2",
    slug: "make-invalid-states-unrepresentable-40np",
    path: "/awwsmm/make-invalid-states-unrepresentable-40np",
    url: "https://dev.to/awwsmm/make-invalid-states-unrepresentable-40np",
    comments_count: 2,
    public_reactions_count: 12,
    collection_id: null,
    published_timestamp: "2024-02-02T17:07:17Z",
    positive_reactions_count: 12,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F0ojao1kjg1132rait4t7.jpg",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F0ojao1kjg1132rait4t7.jpg",
    canonical_url:
      "https://www.awwsmm.com/blog/make-invalid-states-unrepresentable",
    created_at: "2024-02-02T17:07:19Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-02T17:07:17Z",
    last_comment_at: "2024-02-03T03:16:20Z",
    reading_time_minutes: 8,
    tag_list: ["scala", "programming", "discuss", "architecture"],
    tags: "scala, programming, discuss, architecture",
    user: {
      name: "Andrew (he/him)",
      username: "awwsmm",
      twitter_username: null,
      github_username: "awwsmm",
      user_id: 101393,
      website_url: "https://www.awwsmm.com/",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F101393%2F56bf0c89-b8ca-4157-9c3b-79031045a21f.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F101393%2F56bf0c89-b8ca-4157-9c3b-79031045a21f.png",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 1748550,
    title: "AI Grant Traction in OSS Startups",
    description:
      "Last year Nat Friedman and Daniel Gross kicked off the AI Grant and have incubated 60 companies with...",
    readable_publish_date: "Feb 2",
    slug: "ai-grant-traction-in-oss-startups-20aa",
    path: "/opensauced/ai-grant-traction-in-oss-startups-20aa",
    url: "https://dev.to/opensauced/ai-grant-traction-in-oss-startups-20aa",
    comments_count: 4,
    public_reactions_count: 14,
    collection_id: null,
    published_timestamp: "2024-02-02T01:35:19Z",
    positive_reactions_count: 14,
    cover_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F67mkekvcomt1qrurwwi0.png",
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F67mkekvcomt1qrurwwi0.png",
    canonical_url:
      "https://opensauced.pizza/blog/ai-secret-sauce-traction-in-open-source",
    created_at: "2024-02-01T13:33:29Z",
    edited_at: "2024-02-02T02:40:58Z",
    crossposted_at: null,
    published_at: "2024-02-02T01:35:19Z",
    last_comment_at: "2024-02-03T05:10:59Z",
    reading_time_minutes: 5,
    tag_list: ["ai", "opensource"],
    tags: "ai, opensource",
    user: {
      name: "Brian Douglas",
      username: "bdougieyo",
      twitter_username: "bdougieYO",
      github_username: "bdougie",
      user_id: 19970,
      website_url: "https://opensauced.pizza",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F19970%2F6dc0f11e-a4da-4762-aed8-11f70143d31b.jpeg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F19970%2F6dc0f11e-a4da-4762-aed8-11f70143d31b.jpeg",
    },
    organization: {
      name: "OpenSauced",
      username: "opensauced",
      slug: "opensauced",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F2498%2Fa16cc27c-33f9-40b6-92a8-4a43f70a96ef.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F2498%2Fa16cc27c-33f9-40b6-92a8-4a43f70a96ef.png",
    },
  },
  {
    type_of: "article",
    id: 1749781,
    title: "Refining Your Code Craft: A Journey Through 'Five Lines of Code'",
    description:
      "Explore Christian Clausen's \"Five Lines of Code,\" a transformative guide to refactoring that challenges traditional coding practices. Embrace the disciplined approach outlined through Clausen's ten key rules for writing concise, readable, and maintainable code. Focus on simplicity, clear abstraction, and thoughtful naming to elevate code quality. Commit to continuous improvement and refine your craft, making your code not just functional, but truly exceptional.",
    readable_publish_date: "Feb 2",
    slug: "refining-your-code-craft-a-journey-through-five-lines-of-code-4l9f",
    path: "/dev3l/refining-your-code-craft-a-journey-through-five-lines-of-code-4l9f",
    url: "https://dev.to/dev3l/refining-your-code-craft-a-journey-through-five-lines-of-code-4l9f",
    comments_count: 0,
    public_reactions_count: 11,
    collection_id: null,
    published_timestamp: "2024-02-02T16:39:03Z",
    positive_reactions_count: 11,
    cover_image:
      "https://res.cloudinary.com/practicaldev/image/fetch/s--g1vdxIVO--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://i.ibb.co/0QtJbXL/qrqmm-Vzxb-DObdw17u-C51-4-44588.jpg",
    social_image:
      "https://res.cloudinary.com/practicaldev/image/fetch/s--uyPuQTJA--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://i.ibb.co/0QtJbXL/qrqmm-Vzxb-DObdw17u-C51-4-44588.jpg",
    canonical_url:
      "https://dev.to/dev3l/refining-your-code-craft-a-journey-through-five-lines-of-code-4l9f",
    created_at: "2024-02-02T16:17:46Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-02-02T16:39:03Z",
    last_comment_at: "2024-02-02T16:39:03Z",
    reading_time_minutes: 5,
    tag_list: [],
    tags: "",
    user: {
      name: "Justin L Beall",
      username: "dev3l",
      twitter_username: "dev3l_",
      github_username: "DEV3L",
      user_id: 20193,
      website_url: null,
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F20193%2F5aab7437-180a-470e-88f2-26503b1b28ee.png",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F20193%2F5aab7437-180a-470e-88f2-26503b1b28ee.png",
    },
  },
  {
    type_of: "article",
    id: 1747173,
    title: "UI for K8s - 👍🏻 / 👎🏻 ?",
    description:
      "Hi everyone 👋🏻  What are your thoughts on a UI for K8s, and what are your experiences with such...",
    readable_publish_date: "Jan 31",
    slug: "ui-for-k8s--3eoj",
    path: "/cyclops-ui/ui-for-k8s--3eoj",
    url: "https://dev.to/cyclops-ui/ui-for-k8s--3eoj",
    comments_count: 14,
    public_reactions_count: 25,
    collection_id: null,
    published_timestamp: "2024-01-31T12:29:29Z",
    positive_reactions_count: 25,
    cover_image: null,
    social_image:
      "https://media.dev.to/cdn-cgi/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fpy6epne155qi9rn6xqq0.png",
    canonical_url: "https://dev.to/cyclops-ui/ui-for-k8s--3eoj",
    created_at: "2024-01-31T12:29:30Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2024-01-31T12:29:29Z",
    last_comment_at: "2024-02-02T14:41:08Z",
    reading_time_minutes: 1,
    tag_list: ["discuss", "kubernetes"],
    tags: "discuss, kubernetes",
    user: {
      name: "Juraj",
      username: "karadza",
      twitter_username: null,
      github_username: null,
      user_id: 1218189,
      website_url: null,
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1218189%2F97542f79-819b-4ecb-91e5-eff8c4e8ab82.jpg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1218189%2F97542f79-819b-4ecb-91e5-eff8c4e8ab82.jpg",
    },
    organization: {
      name: "Cyclops UI",
      username: "cyclops-ui",
      slug: "cyclops-ui",
      profile_image:
        "https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F7917%2F676427c4-990f-4e32-85cb-27c4767b311d.jpeg",
      profile_image_90:
        "https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F7917%2F676427c4-990f-4e32-85cb-27c4767b311d.jpeg",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
];
